# Generated by Django 3.1.5 on 2021-01-25 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210125_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '오픈튜토리얼스 사용자', 'verbose_name_plural': 'o2 사용자'},
        ),
        migrations.AddField(
            model_name='members',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='가입일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='수정일시'),
            preserve_default=False,
        ),
    ]
