# Generated by Django 3.1.5 on 2021-01-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210125_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
