# Generated by Django 3.1.5 on 2021-01-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_members'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table=None,
        ),
    ]
